# Generated by Django 3.2.5 on 2021-07-29 20:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('ora_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cod_secret', models.UUIDField(default=uuid.UUID('e539e604-32b1-4716-bec6-b205b98f9a33'))),
                ('prima_logare', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_logare', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
