# Generated by Django 3.2.5 on 2021-07-29 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='ipuri',
            field=models.ManyToManyField(blank=True, to='backend.IP'),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_secret',
            field=models.UUIDField(default=uuid.UUID('32b0e9c1-f781-4597-a977-710808dd4b5a')),
        ),
    ]
