# Generated by Django 3.2.5 on 2021-07-30 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210730_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizator',
            name='email',
        ),
        migrations.AddField(
            model_name='utilizator',
            name='parola',
            field=models.UUIDField(default=uuid.UUID('47c5cb73-7094-4eb0-9971-aca7595bb270')),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_secret',
            field=models.UUIDField(default=uuid.UUID('de0027fa-aae0-4bd2-835d-42963dc14262')),
        ),
    ]
