# Generated by Django 3.2.5 on 2021-08-01 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210801_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='ultima_executare',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_secret',
            field=models.CharField(default='a590f6a3-162f-443f-bf3b-e2651577edbe', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='parola',
            field=models.CharField(default='48b9a118-ba01-4c81-9cb3-545395094e0d', max_length=100),
        ),
    ]
