# Generated by Django 3.2.5 on 2021-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210801_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizator',
            name='ultima_executare',
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_secret',
            field=models.CharField(default='f6557e25-e4f0-43f6-b9de-0b3b555ee0e2', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='parola',
            field=models.CharField(default='c7dec111-7f08-4abf-afe6-f7d22fbc3a01', max_length=100),
        ),
    ]
