# Generated by Django 3.2.5 on 2021-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210801_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='executabil',
            name='tip_executabil',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_secret',
            field=models.CharField(default='ec1a23a3-b664-41f6-8b71-c9649ec8585b', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='parola',
            field=models.CharField(default='45f7e539-c61d-477f-9cb0-94fff8fdafc5', max_length=100),
        ),
    ]
